name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ia codul
        uses: actions/checkout@v4

      - name: Pune Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Pregateste Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Genereaza gradlew
        run: gradle wrapper --gradle-version 8.9

      - name: Setează drepturi gradlew
        run: chmod +x gradlew

      - name: Construieste APK-ul
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Urca APK-ul
        uses: actions/upload-artifact@v4
        with:
          name: Tetris3D-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
